mbsandbox=http://mbsandbox.org/~jonnyjd/swagger/docs
localhost=http://localhost/swagger-docs

mbsandbox:
	sed -i 's|\(\s*"basePath":\).*|\1"$(mbsandbox)",|' api-docs.json

local:
	sed -i 's|\(\s*"basePath":\).*|\1"$(localhost)",|' api-docs.json
